export const FETCH_EPISODES_SUCCESS = 'FETCH_EPISODES_SUCCESS';
export const FETCH_EPISODES_FAIL = 'FETCH_EPISODES_FAIL';
export const FETCH_EPISODES_DETAILS_SUCCESS = 'FETCH_EPISODES_DETAILS_SUCCESS';
export const FETCH_EPISODES_DETAILS_FAIL = 'FETCH_EPISODES_DETAILS_FAILS';